### ISSUE TITLE
An unexpected error occurred from ISV code

### ISSUE THREAD

**Issue by larachpatino** [a33ik/HtmlLocalization#1]
I have the web resources index.html and index.js. I added dependencies to the HtmlLocalization.js to both web resources. As a result, I saw the following error:

An unexpected error occurred from ISV code.(ErrorType = ClientError) Unexpected exception from plug-in (Execute): AB.HtmlLocalization.Plugins.GetLocalizations:System.Xml.XmlException: Data et the root level is invalid. Line 1, position 1.

To fix it Andrew found out that I have to remove the dependency to HtmlLocalizatoin.js from  index.js. So only index.html has a dependency to HtmlLocalization.js

**Comment by AndrewButenko** [comment]
Fixed in latest version
