### ISSUE TITLE
Invalid Argument. The value passes for Condition Operator. In is empty

### ISSUE THREAD

**Issue by larachpatino** [a33ik/HtmlLocalization#2]
I have two web resources index.html and index.js. I added dependencies to all .resx web resources and HtmlLocalizatoin.js to index.html. I did not add any dependencies to index.js.

That caused the following error:  
Invalid Argument. The value passes for Condition Operator. In is empty

Andrew found out that to fix the issue I should add the dependencies to .resx files to index.js.
and the dependency to HtmlLocalizatoin.js to the index.html web resource.

**Comment by AndrewButenko** [comment]
Fixed in latest version
