### ISSUE TITLE
Unexpected token u in JSON HtmlLocalization.js:27 

### ISSUE THREAD

**Issue by larachpatino** [a33ik/HtmlLocalization#3]
I added a html window in a Unified Interface. for that I have 2 web resources index.html and index.js.

I added a dependency to HtmlLocalizatoin.js to index.html, and depencendies to all .resx web resources to index.js, when launching the page I got the following error:

Uncaught (in promise) SyntaxError: Unexpected token u in JSON HtmlLocalization.js:27 at postion 0
at JSON.parse(<anonymous>)
at success (HtmlLocalization.js:27)

During debugging result.responseText inHtmlLocalization.js:27 was undefined

**Comment by AndrewButenko** [comment]
I replaced parsing of result.responseText with json function. More information is available here - https://www.inogic.com/blog/2019/01/execute-action-using-xrm-webapi-online-execute-in-dynamics-365-crm-v9-0/
