### ISSUE TITLE
What is this solution for?

### ISSUE THREAD

**Issue by ArtKarp** [a33ik/HtmlLocalization#4]
I saw this on Twitter and thought I would check it out. It looks interesting, but I seem to be missing something. 

Do you have any examples of how and why you would use this solution?   I am a bit confused.  Since D365 already has the ability to localize text, I am not sure what your solution is for.  

If I build a form wizard using HTML/JS/WebAPI saved as a web resource and launched from the ribbon, would it be able to help with that localization?  If not that, then what is the use case? What are you localizing?  

Thanks
-Art

**Comment by AndrewButenko** [comment]
Hello Art,
Here is explanation - https://butenko.pro/2018/12/18/how-to-use-xrm-utility-getresourcestring-in-html-webresources/

But generally speaking Xrm.Utility.getResourceString doesn't work properly for Html/JS webresources and this solution helps in resolution of this issue.
